/**
 * The armoury, generated from the spreadsheet by `scripts/build-weapons.mjs`.
 *
 * Do not edit by hand: edit `scripts/weapons-source.csv` and re-run the script.
 *
 * `familiarity` is 0-5 where 0 means "used big time" and 5 means "never really
 * touched it". It is the only opinion in this file; every weighting decision is
 * made from it at runtime.
 */

export interface Weapon {
  readonly name: string;
  readonly type: string;
  readonly dlc: boolean;
  readonly familiarity: number;
  readonly earliest_zone: number;
}

export const WEAPONS: readonly Weapon[] = [
  { name: 'Battle Axe', type: 'Axe', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Celebrant\'s Cleaver', type: 'Axe', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Death Knight\'s Twin Axes', type: 'Axe', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Forked Hatchet', type: 'Axe', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Forked-Tongue Hatchet', type: 'Axe', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Hand Axe', type: 'Axe', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Highland Axe', type: 'Axe', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Icerind Hatchet', type: 'Axe', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Iron Cleaver', type: 'Axe', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Jawbone Axe', type: 'Axe', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Messmer Soldier\'s Axe', type: 'Axe', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Ripple Blade', type: 'Axe', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Rosus\' Axe', type: 'Axe', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Sacrificial Axe', type: 'Axe', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Smithscript Axe', type: 'Axe', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Stormhawk Axe', type: 'Axe', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Warped Axe', type: 'Axe', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Backhand Blade', type: 'Backhand Blade', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Curseblade\'s Cirque', type: 'Backhand Blade', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Smithscript Cirque', type: 'Backhand Blade', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Hand Ballista', type: 'Ballista', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Jar Cannon', type: 'Ballista', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Rabbath\'s Cannon', type: 'Ballista', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Beast Claw', type: 'Beast Claw', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Claws of Night', type: 'Beast Claw', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Red Bear\'s Claw', type: 'Beast Claw', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Albinauric Bow', type: 'Bow', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Ansbach\'s Longbow', type: 'Bow', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Black Bow', type: 'Bow', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Erdtree Bow', type: 'Bow', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Horn Bow', type: 'Bow', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Longbow', type: 'Bow', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Pulley Bow', type: 'Bow', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Serpent Bow', type: 'Bow', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Bloodhound Claws', type: 'Claw', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Hookclaws', type: 'Claw', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Raptor Talons', type: 'Claw', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Venomous Fang', type: 'Claw', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Ancient Meteoric Ore Greatsword', type: 'Colossal Sword', dlc: true, familiarity: 3, earliest_zone: 1 },
  { name: 'Fire Knight\'s Greatsword', type: 'Colossal Sword', dlc: true, familiarity: 0, earliest_zone: 1 },
  { name: 'Godslayer\'s Greatsword', type: 'Colossal Sword', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Grafted Blade Greatsword', type: 'Colossal Sword', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Greatsword', type: 'Colossal Sword', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Greatsword of Radahn (Light)', type: 'Colossal Sword', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Greatsword of Radahn (Lord)', type: 'Colossal Sword', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Maliketh\'s Black Blade', type: 'Colossal Sword', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Moonrithyll\'s Knight Sword', type: 'Colossal Sword', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Royal Greatsword', type: 'Colossal Sword', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Ruins Greatsword', type: 'Colossal Sword', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Starscourge Greatsword', type: 'Colossal Sword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Troll Knight\'s Sword', type: 'Colossal Sword', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Troll\'s Golden Sword', type: 'Colossal Sword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Watchdog\'s Greatsword', type: 'Colossal Sword', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Zweihander', type: 'Colossal Sword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Anvil Hammer', type: 'Colossal Weapon', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Axe of Godfrey', type: 'Colossal Weapon', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Bloodfiend\'s Arm', type: 'Colossal Weapon', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Devonia\'s Hammer', type: 'Colossal Weapon', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Dragon Greatclaw', type: 'Colossal Weapon', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Duelist Greataxe', type: 'Colossal Weapon', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Envoy\'s Greathorn', type: 'Colossal Weapon', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Fallingstar Beast Jaw', type: 'Colossal Weapon', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Gazing Finger', type: 'Colossal Weapon', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Ghiza\'s Wheel', type: 'Colossal Weapon', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Giant-Crusher', type: 'Colossal Weapon', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Golem\'s Halberd', type: 'Colossal Weapon', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Great Club', type: 'Colossal Weapon', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Prelate\'s Inferno Crozier', type: 'Colossal Weapon', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Rotten Greataxe', type: 'Colossal Weapon', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Rotten Staff', type: 'Colossal Weapon', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Shadow Sunflower Blossom', type: 'Colossal Weapon', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Staff of the Avatar', type: 'Colossal Weapon', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Troll\'s Hammer', type: 'Colossal Weapon', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Watchdog\'s Staff', type: 'Colossal Weapon', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Arbalest', type: 'Crossbow', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Crepus\'s Black-Key Crossbow', type: 'Crossbow', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Full Moon Crossbow', type: 'Crossbow', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Heavy Crossbow', type: 'Crossbow', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Light Crossbow', type: 'Crossbow', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Pulley Crossbow', type: 'Crossbow', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Repeating Crossbow', type: 'Crossbow', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Soldier\'s Crossbow', type: 'Crossbow', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Spread Crossbow', type: 'Crossbow', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Beastman\'s Cleaver', type: 'Curved Greatsword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Bloodhound\'s Fang', type: 'Curved Greatsword', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Dismounter', type: 'Curved Greatsword', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Horned Warrior\'s Greatsword', type: 'Curved Greatsword', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Magma Wyrm\'s Scalesword', type: 'Curved Greatsword', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Monk\'s Flameblade', type: 'Curved Greatsword', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Morgott\'s Cursed Sword', type: 'Curved Greatsword', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Omen Cleaver', type: 'Curved Greatsword', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Onyx Lord\'s Greatsword', type: 'Curved Greatsword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Zamor Curved Sword', type: 'Curved Greatsword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Bandit\'s Curved Sword', type: 'Curved Sword', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Beastman\'s Curved Sword', type: 'Curved Sword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Dancing Blade of Ranah', type: 'Curved Sword', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Eclipse Shotel', type: 'Curved Sword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Falchion', type: 'Curved Sword', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Falx', type: 'Curved Sword', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Flowing Curved Sword', type: 'Curved Sword', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Grossmesser', type: 'Curved Sword', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Horned Warrior\'s Sword', type: 'Curved Sword', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Magma Blade', type: 'Curved Sword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Mantis Blade', type: 'Curved Sword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Nox Flowing Sword', type: 'Curved Sword', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Scavenger\'s Curved Sword', type: 'Curved Sword', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Scimitar', type: 'Curved Sword', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Serpent-God\'s Curved Sword', type: 'Curved Sword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Shamshir', type: 'Curved Sword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Shotel', type: 'Curved Sword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Spirit Sword', type: 'Curved Sword', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Wing of Astel', type: 'Curved Sword', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Black Knife', type: 'Dagger', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Blade of Calling', type: 'Dagger', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Bloodstained Dagger', type: 'Dagger', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Celebrant\'s Sickle', type: 'Dagger', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Cinquedea', type: 'Dagger', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Crystal Knife', type: 'Dagger', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Dagger', type: 'Dagger', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Erdsteel Dagger', type: 'Dagger', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Glintstone Kris', type: 'Dagger', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Great Knife', type: 'Dagger', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Ivory Sickle', type: 'Dagger', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Main-gauche', type: 'Dagger', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Misericorde', type: 'Dagger', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Parrying Dagger', type: 'Dagger', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Reduvia', type: 'Dagger', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Scorpion\'s Stinger', type: 'Dagger', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Wakizashi', type: 'Dagger', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Caestus', type: 'Fist', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Cipher Pata', type: 'Fist', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Clinging Bone', type: 'Fist', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Golem Fist', type: 'Fist', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Grafted Dragon', type: 'Fist', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Iron Ball', type: 'Fist', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Katar', type: 'Fist', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Madding Hand', type: 'Fist', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Pata', type: 'Fist', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Poisoned Hand', type: 'Fist', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Spiked Caestus', type: 'Fist', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Star Fist', type: 'Fist', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Thiollier\'s Hidden Needle', type: 'Fist', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Veteran\'s Prosthesis', type: 'Fist', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Bastard\'s Stars', type: 'Flail', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Chainlink Flail', type: 'Flail', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Family Heads', type: 'Flail', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Flail', type: 'Flail', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Nightrider Flail', type: 'Flail', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Serpent Flail', type: 'Flail', dlc: true, familiarity: 2, earliest_zone: 1 },
  { name: 'Academy Glintstone Staff', type: 'Glintstone Staff', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Albinauric Staff', type: 'Glintstone Staff', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Astrologer\'s Staff', type: 'Glintstone Staff', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Azur\'s Glintstone Staff', type: 'Glintstone Staff', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Carian Glintblade Staff', type: 'Glintstone Staff', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Carian Glintstone Staff', type: 'Glintstone Staff', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Carian Regal Scepter', type: 'Glintstone Staff', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Crystal Staff', type: 'Glintstone Staff', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Demi-Human Queen\'s Staff', type: 'Glintstone Staff', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Digger\'s Staff', type: 'Glintstone Staff', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Gelmir Glintstone Staff', type: 'Glintstone Staff', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Glintstone Staff', type: 'Glintstone Staff', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Lusat\'s Glintstone Staff', type: 'Glintstone Staff', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Maternal Staff', type: 'Glintstone Staff', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Meteorite Staff', type: 'Glintstone Staff', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Prince of Death\'s Staff', type: 'Glintstone Staff', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Rotten Crystal Staff', type: 'Glintstone Staff', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Staff of Loss', type: 'Glintstone Staff', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Staff of the Great Beyond', type: 'Glintstone Staff', dlc: true, familiarity: 2, earliest_zone: 1 },
  { name: 'Staff of the Guilty', type: 'Glintstone Staff', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Black Steel Greathammer', type: 'Great Hammer', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Smithscript Greathammer', type: 'Great Hammer', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Dragon-Hunter\'s Great Katana', type: 'Great Katana', dlc: true, familiarity: 1, earliest_zone: 1 },
  { name: 'Great Katana', type: 'Great Katana', dlc: true, familiarity: 0, earliest_zone: 1 },
  { name: 'Rakshasa\'s Great Katana', type: 'Great Katana', dlc: true, familiarity: 3, earliest_zone: 1 },
  { name: 'Barbed Staff-Spear', type: 'Great Spear', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Bloodfiend\'s Sacred Spear', type: 'Great Spear', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Lance', type: 'Great Spear', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Messmer Soldier\'s Spear', type: 'Great Spear', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Mohgwyn\'s Sacred Spear', type: 'Great Spear', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Serpent-Hunter', type: 'Great Spear', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Siluria\'s Tree', type: 'Great Spear', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Spear of the Impaler', type: 'Great Spear', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Treespear', type: 'Great Spear', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Vyke\'s War Spear', type: 'Great Spear', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Axe of Godrick', type: 'Greataxe', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Bonny Butchering Knife', type: 'Greataxe', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Butchering Knife', type: 'Greataxe', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Crescent Moon Axe', type: 'Greataxe', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Death Knight\'s Longhaft Axe', type: 'Greataxe', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Executioner\'s Greataxe', type: 'Greataxe', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Gargoyle\'s Black Axe', type: 'Greataxe', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Gargoyle\'s Great Axe', type: 'Greataxe', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Great Omenkiller Cleaver', type: 'Greataxe', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Greataxe', type: 'Greataxe', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Longhaft Axe', type: 'Greataxe', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Putrescence Cleaver', type: 'Greataxe', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Rusted Anchor', type: 'Greataxe', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Winged Greathorn', type: 'Greataxe', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Erdtree Greatbow', type: 'Greatbow', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Golem Greatbow', type: 'Greatbow', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Greatbow', type: 'Greatbow', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Igon\'s Greatbow', type: 'Greatbow', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Lion Greatbow', type: 'Greatbow', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Alabaster Lord\'s Sword', type: 'Greatsword', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Banished Knight\'s Greatsword', type: 'Greatsword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Bastard Sword', type: 'Greatsword', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Blasphemous Blade', type: 'Greatsword', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Claymore', type: 'Greatsword', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Dark Moon Greatsword', type: 'Greatsword', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Death\'s Poker', type: 'Greatsword', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Flamberge', type: 'Greatsword', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Forked Greatsword', type: 'Greatsword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Freyja\'s Greatsword', type: 'Greatsword', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Gargoyle\'s Blackblade', type: 'Greatsword', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Gargoyle\'s Greatsword', type: 'Greatsword', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Golden Order Greatsword', type: 'Greatsword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Greatsword of Damnation', type: 'Greatsword', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Greatsword of Solitude', type: 'Greatsword', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Helphen\'s Steeple', type: 'Greatsword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Inseparable Sword', type: 'Greatsword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Iron Greatsword', type: 'Greatsword', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Knight\'s Greatsword', type: 'Greatsword', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Lizard Greatsword', type: 'Greatsword', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Lordsworn\'s Greatsword', type: 'Greatsword', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Marais Executioner\'s Sword', type: 'Greatsword', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Ordovis\'s Greatsword', type: 'Greatsword', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Queelign\'s Greatsword', type: 'Greatsword', dlc: true, familiarity: 0, earliest_zone: 1 },
  { name: 'Sacred Relic Sword', type: 'Greatsword', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Sword of Milos', type: 'Greatsword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Banished Knight\'s Halberd', type: 'Halberd', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Commander\'s Standard', type: 'Halberd', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Dragon Halberd', type: 'Halberd', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Gargoyle\'s Black Halberd', type: 'Halberd', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Gargoyle\'s Halberd', type: 'Halberd', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Glaive', type: 'Halberd', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Golden Halberd', type: 'Halberd', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Guardian\'s Swordspear', type: 'Halberd', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Halberd', type: 'Halberd', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Loretta\'s War Sickle', type: 'Halberd', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Lucerne', type: 'Halberd', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Nightrider Glaive', type: 'Halberd', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Pest\'s Glaive', type: 'Halberd', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Poleblade of the Bud', type: 'Halberd', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Ripple Crescent Halberd', type: 'Halberd', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Spirit Glaive', type: 'Halberd', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Vulgar Militia Saw', type: 'Halberd', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Vulgar Militia Shotel', type: 'Halberd', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Club', type: 'Hammer', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Curved Club', type: 'Hammer', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Envoy\'s Horn', type: 'Hammer', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Flowerstone Gavel', type: 'Hammer', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Hammer', type: 'Hammer', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Mace', type: 'Hammer', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Marika\'s Hammer', type: 'Hammer', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Monk\'s Flamemace', type: 'Hammer', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Morning Star', type: 'Hammer', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Nox Flowing Hammer', type: 'Hammer', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Ringed Finger', type: 'Hammer', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Scepter of the All-Knowing', type: 'Hammer', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Spiked Club', type: 'Hammer', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Stone Club', type: 'Hammer', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Varre\'s Bouquet', type: 'Hammer', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Warpick', type: 'Hammer', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Dane\'s Footwork', type: 'Hand-to-Hand Art', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Dryleaf Arts', type: 'Hand-to-Hand Art', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Bloody Helice', type: 'Heavy Thrusting Sword', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Dragon King\'s Cragblade', type: 'Heavy Thrusting Sword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Godskin Stitcher', type: 'Heavy Thrusting Sword', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Great Epee', type: 'Heavy Thrusting Sword', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Sword Lance', type: 'Heavy Thrusting Sword', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Dragonscale Blade', type: 'Katana', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Hand of Malenia', type: 'Katana', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Meteoric Ore Blade', type: 'Katana', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Moonveil', type: 'Katana', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Nagakiba', type: 'Katana', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Rivers of Blood', type: 'Katana', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Serpentbone Blade', type: 'Katana', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Star-Lined Sword', type: 'Katana', dlc: true, familiarity: 3, earliest_zone: 1 },
  { name: 'Sword of Night', type: 'Katana', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Uchigatana', type: 'Katana', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Bone Bow', type: 'Light Bow', dlc: true, familiarity: 2, earliest_zone: 1 },
  { name: 'Composite Bow', type: 'Light Bow', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Harp Bow', type: 'Light Bow', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Misbegotten Shortbow', type: 'Light Bow', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Red Branch Shortbow', type: 'Light Bow', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Shortbow', type: 'Light Bow', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Leda\'s Sword', type: 'Light Greatsword', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Milady', type: 'Light Greatsword', dlc: true, familiarity: 0, earliest_zone: 1 },
  { name: 'Rellana\'s Twin Blades', type: 'Light Greatsword', dlc: true, familiarity: 3, earliest_zone: 1 },
  { name: 'Chilling Perfume Bottle', type: 'Perfume Bottle', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Deadly Poison Perfume Bottle', type: 'Perfume Bottle', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Firespark Perfume Bottle', type: 'Perfume Bottle', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Frenzyflame Perfume Bottle', type: 'Perfume Bottle', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Lightning Perfume Bottle', type: 'Perfume Bottle', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Grave Scythe', type: 'Reaper', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Halo Scythe', type: 'Reaper', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Obsidian Lamina', type: 'Reaper', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Scythe', type: 'Reaper', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Winged Scythe', type: 'Reaper', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Clawmark Seal', type: 'Sacred Seal', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Dragon Communion Seal', type: 'Sacred Seal', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Dryleaf Seal', type: 'Sacred Seal', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Erdtree Seal', type: 'Sacred Seal', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Finger Seal', type: 'Sacred Seal', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Fire Knight\'s Seal', type: 'Sacred Seal', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Frenzied Flame Seal', type: 'Sacred Seal', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Giant\'s Seal', type: 'Sacred Seal', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Godslayer\'s Seal', type: 'Sacred Seal', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Golden Order Seal', type: 'Sacred Seal', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Gravel Stone Seal', type: 'Sacred Seal', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Spiraltree Seal', type: 'Sacred Seal', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Bloodfiend\'s Fork', type: 'Spear', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Bolt of Gransax', type: 'Spear', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Celebrant\'s Rib-Rake', type: 'Spear', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Clayman\'s Harpoon', type: 'Spear', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Cleanrot Spear', type: 'Spear', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Cross-Naginata', type: 'Spear', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Crystal Spear', type: 'Spear', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Death Ritual Spear', type: 'Spear', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Inquisitor\'s Girandole', type: 'Spear', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Iron Spear', type: 'Spear', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Partisan', type: 'Spear', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Pike', type: 'Spear', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Rotten Crystal Spear', type: 'Spear', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Short Spear', type: 'Spear', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Smithscript Spear', type: 'Spear', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Spear', type: 'Spear', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Spiked Spear', type: 'Spear', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Swift Spear', type: 'Spear', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Torchpole', type: 'Spear', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Broadsword', type: 'Straight Sword', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Cane Sword', type: 'Straight Sword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Carian Knight\'s Sword', type: 'Straight Sword', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Coded Sword', type: 'Straight Sword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Crystal Sword', type: 'Straight Sword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Fire Knight\'s Shortsword', type: 'Straight Sword', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Golden Epitaph', type: 'Straight Sword', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Lazuli Glintstone Sword', type: 'Straight Sword', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Longsword', type: 'Straight Sword', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Lordsworn\'s Straight Sword', type: 'Straight Sword', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Miquellan Knight\'s Sword', type: 'Straight Sword', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Noble\'s Slender Sword', type: 'Straight Sword', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Ornamental Straight Sword', type: 'Straight Sword', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Regalia of Eochaid', type: 'Straight Sword', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Rotten Crystal Sword', type: 'Straight Sword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Short Sword', type: 'Straight Sword', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Stone-Sheathed Sword', type: 'Straight Sword', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Sword of Darkness', type: 'Straight Sword', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Sword of Light', type: 'Straight Sword', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Sword of Night and Flame', type: 'Straight Sword', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Sword of St. Trina', type: 'Straight Sword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Velvet Sword of St. Trina', type: 'Straight Sword', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Warhawk\'s Talon', type: 'Straight Sword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Weathered Straight Sword', type: 'Straight Sword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Smithscript Dagger', type: 'Throwing Blade', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Carian Thrusting Shield', type: 'Thrusting Shield', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Dueling Shield', type: 'Thrusting Shield', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Antspur Rapier', type: 'Thrusting Sword', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Carian Sorcery Sword', type: 'Thrusting Sword', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Cleanrot Knight\'s Sword', type: 'Thrusting Sword', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Estoc', type: 'Thrusting Sword', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Frozen Needle', type: 'Thrusting Sword', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Noble\'s Estoc', type: 'Thrusting Sword', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Rapier', type: 'Thrusting Sword', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Rogier\'s Rapier', type: 'Thrusting Sword', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Beast-Repellent Torch', type: 'Torch', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Ghostflame Torch', type: 'Torch', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Lamenting Visage', type: 'Torch', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Nanaya\'s Torch', type: 'Torch', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Sentry\'s Torch', type: 'Torch', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'St. Trina\'s Torch', type: 'Torch', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Steel-Wire Torch', type: 'Torch', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Torch', type: 'Torch', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Black Steel Twinblade', type: 'Twinblade', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Eleonora\'s Poleblade', type: 'Twinblade', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Euporia', type: 'Twinblade', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Gargoyle\'s Black Blades', type: 'Twinblade', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Gargoyle\'s Twinblade', type: 'Twinblade', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Godskin Peeler', type: 'Twinblade', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Twinblade', type: 'Twinblade', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Twinned Knight Swords', type: 'Twinblade', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Battle Hammer', type: 'Warhammer', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Beastclaw Greathammer', type: 'Warhammer', dlc: false, familiarity: 0, earliest_zone: 1 },
  { name: 'Brick Hammer', type: 'Warhammer', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Celebrant\'s Skull', type: 'Warhammer', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Cranial Vessel Candlestand', type: 'Warhammer', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Curved Great Club', type: 'Warhammer', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Devourer\'s Scepter', type: 'Warhammer', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Envoy\'s Long Horn', type: 'Warhammer', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Great Mace', type: 'Warhammer', dlc: false, familiarity: 3, earliest_zone: 1 },
  { name: 'Great Stars', type: 'Warhammer', dlc: false, familiarity: 1, earliest_zone: 1 },
  { name: 'Greathorn Hammer', type: 'Warhammer', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Large Club', type: 'Warhammer', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Pickaxe', type: 'Warhammer', dlc: false, familiarity: 2, earliest_zone: 1 },
  { name: 'Rotten Battle Hammer', type: 'Warhammer', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Giant\'s Red Braid', type: 'Whip', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Hoslow\'s Petal Whip', type: 'Whip', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Magma Whip Candlestick', type: 'Whip', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Thorned Whip', type: 'Whip', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Tooth Whip', type: 'Whip', dlc: true, familiarity: 5, earliest_zone: 1 },
  { name: 'Urumi', type: 'Whip', dlc: false, familiarity: 5, earliest_zone: 1 },
  { name: 'Whip', type: 'Whip', dlc: false, familiarity: 5, earliest_zone: 1 },
];

/** Every distinct weapon type in the sheet, alphabetically. */
export const WEAPON_TYPES: readonly string[] = [
  'Axe',
  'Backhand Blade',
  'Ballista',
  'Beast Claw',
  'Bow',
  'Claw',
  'Colossal Sword',
  'Colossal Weapon',
  'Crossbow',
  'Curved Greatsword',
  'Curved Sword',
  'Dagger',
  'Fist',
  'Flail',
  'Glintstone Staff',
  'Great Hammer',
  'Great Katana',
  'Great Spear',
  'Greataxe',
  'Greatbow',
  'Greatsword',
  'Halberd',
  'Hammer',
  'Hand-to-Hand Art',
  'Heavy Thrusting Sword',
  'Katana',
  'Light Bow',
  'Light Greatsword',
  'Perfume Bottle',
  'Reaper',
  'Sacred Seal',
  'Spear',
  'Straight Sword',
  'Throwing Blade',
  'Thrusting Shield',
  'Thrusting Sword',
  'Torch',
  'Twinblade',
  'Warhammer',
  'Whip',
];
